#!/bin/sh
set -e

case "$1" in
  configure)
    logdir="/var/log/nginx"
    # Ensure secure permissions (CVE-2013-0337)
    # http://bugs.debian.org/701112
    #
    # nginx uses 0755 for log files making them world readable,
    # we fix that by using 0750 for the log directory.
    #
    # Allow local admin to override:
    # e.g. dpkg-statoverride --add root adm 0755 /var/log/nginx
    if ! dpkg-statoverride --list "$logdir" >/dev/null; then
      chown www-data:adm $logdir
      chmod 0750 $logdir
    fi
    # If a symlink doesn't exist and can be created, then create it.
    if [ -z $2 ] && [ ! -e /etc/nginx/sites-enabled/default ] &&
       [ -d /etc/nginx/sites-enabled ] && [ -d /etc/nginx/sites-available ]; then
      ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask nginx.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled nginx.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable nginx.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state nginx.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/nginx" ]; then
	if [ ! -e "/etc/init/nginx.conf" ]; then
		update-rc.d nginx defaults >/dev/null
	fi
fi
# End automatically added section


exit 0
